cognite:
  project:
  tenant_id:
  cdf_cluster:
  client_id:
dm_clients:
  space:
  datamodel:
  schema_version:
  max_tries: 5

local:
  schema_file: path/to/schema.graphql
  schema_module: python.path.to.your_domain.schema
